### ISSUE TITLE
セパレータ ';' が rack 1.6.0 で動作しない

### ISSUE THREAD

**Issue by Nyoho** [hiki/hiki#62]
https://github.com/hiki/hiki/commit/dfa886b3ec8d0055bbca291b818932cfef1acd83 の bundle update により rack が 1.6.0 になり、セパレータの ';' がセパレータとして動作しなくなっているようです。

よって、hike を rack アプリとして使うと、例えば /?c=admin;conf=hoge のとき key c の値が admin;conf=hoge となってしまい、管理画面や、attach が正常に動いていません。

おそらく rack の https://github.com/rack/rack/commit/71c69113f269f04207157bee6c197b5675f3df61#diff-345b5336fcb3ce47a50decd2176d79e8R331 このコミットが 1.6.0 で取り込まれたからだと思います。
(現在: https://github.com/rack/rack/blob/master/lib%2Frack%2Frequest.rb#L369 )
これは POST の文字列中の ';' をセパレータとしないようにするためのはずで、GET のときにも適用されてしまったのはバグなのではないかと考えていますがどうでしょうか。

これは hiki をなおすのではなく、rack 自体をなおすべきでしょうか。

とりあえず、`gem 'rack', "~> 1.5.0"` とすれば正常に動きます。

**Comment by okkez** [comment]
コミットログとテストが一致していないように見えるので rack の方で聞いてみるのがいいと思います。

**Comment by Nyoho** [comment]
ありがとうございます。聞いてみたいと思います。

**Comment by okkez** [comment]
rack 1.6.4 で試したら動いているので close します。
