### ISSUE TITLE
選択可能なプラグインがありません

### ISSUE THREAD

**Issue by daddygongon** [hiki/hiki#64]
mathjaxをhikiに組み込もうと思いたったのですが，どうせ拡張するなら最新版にと思い，githubからforkして，rackupで動かしてみたのですが，プラグイン選択で
「選択可能なプラグインはありません．」
と表示されます．

hikiconf.rbのdatapathを修正しただけですが，他に操作が必要でしょうか?

**Comment by okkez** [comment]
今の master は大改造中なので一部動かないです。
試していないですが plugin のところは hikiconf.rb で `@plugin_path` を設定すると動くと思います。

**Comment by daddygongon** [comment]
./hikiconf.rbで
@plugin_path     = './lib/hiki/plugin'
を追加してみましたが，「選択可能なプラグインはありません．」でした．
手元で動いているversion(Hiki 1.0.0 (2013-03-30))で作業します．
gem化がんばってください．お手伝いできればいいのですが．．

**Comment by okkez** [comment]
申し訳ないです :bow:
なるべく早く直すのでしばらくお待ちください :pray:

あと試すとしたら、`@plugin_path` を相対パスではなく絶対パスで書くくらいでしょうか。。。

**Comment by daddygongon** [comment]
./lib/hiki/plugin/01sp/rbの
#*@sp_path = *(@conf["#{SP_PREFIX}.path"] || "#{PATH}/misc/plugin")                           
*@sp_path = *(@conf["#{SP_PREFIX}.path"] || "#{PATH}/../../misc/plugin")

**Comment by daddygongon** [comment]
すいません．へんなところでreturn押してしまって．．．

pluginですが，
./lib/hiki/plugin/01sp/rbの
*@sp_path = *(@conf["#{SP_PREFIX}.path"] || "#{PATH}/misc/plugin")
を
*@sp_path = *(@conf["#{SP_PREFIX}.path"] || "#{PATH}/../../misc/plugin")
に変更したところ，表示されました．

pluginの入っているfolderを移動させるべきか，悩んでいまはこれで行っています．

試してみたpluginの報告です．
* attach_anchor 表示はされるが，data/cache/attachの生成以降は未動作
* bbs.rb undefined method
* search.rb 動いているみたい
* edit_user.rb動いているみたい

pull requestさせていただいてもいいんですが，pressureになるでしょうから，
もしお手伝いできることあればお知らせください．
